# Generated by Django 3.2.8 on 2021-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0002_class_time_table_faculty_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects_table',
            name='subject_branch',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
