# Generated by Django 3.2.8 on 2021-11-04 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0003_subjects_table_subject_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects_table',
            name='subject_branch',
        ),
        migrations.AddField(
            model_name='subjects_table',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='v_1.department_table'),
            preserve_default=False,
        ),
    ]
