# Generated by Django 3.2.8 on 2021-11-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0004_auto_20211104_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_table',
            fields=[
                ('block_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timings_table',
            fields=[
                ('timing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timing_space', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Week_table',
            fields=[
                ('week_id', models.IntegerField(primary_key=True, serialize=False)),
                ('week_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room_table',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_number', models.IntegerField()),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.block_table')),
            ],
        ),
        migrations.CreateModel(
            name='Branch_table',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.block_table')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.department_table')),
            ],
        ),
        migrations.AlterField(
            model_name='class_time_table',
            name='Room_with_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.room_table'),
        ),
        migrations.AlterField(
            model_name='class_time_table',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.branch_table'),
        ),
        migrations.AlterField(
            model_name='class_time_table',
            name='timing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.timings_table'),
        ),
        migrations.AlterField(
            model_name='class_time_table',
            name='weekday_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.week_table'),
        ),
    ]
