# Generated by Django 3.2.8 on 2021-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0007_alter_faculty_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_table',
            name='faculty_id',
            field=models.IntegerField(unique=True),
        ),
    ]
