# Generated by Django 3.2.8 on 2021-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0008_alter_faculty_table_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_table',
            name='subject_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
