# Generated by Django 3.2.8 on 2021-11-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0011_alter_subjects_table_semester_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_fac_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.branch_table')),
                ('faculty_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.faculty_table')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.section_table')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.semester_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.subjects_table')),
            ],
        ),
    ]
