# Generated by Django 3.2.8 on 2021-12-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0013_rename_faculty_table_sub_fac_relation_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_information_table',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=300)),
                ('lab_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assistant', to='v_1.faculty_table')),
                ('lab_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.room_table')),
                ('lab_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.department_table')),
                ('lab_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.faculty_table')),
            ],
        ),
        migrations.CreateModel(
            name='lab_time_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.branch_table')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.lab_information_table')),
                ('lab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.subjects_table')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.section_table')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.semester_table')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.timings_table')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.week_table')),
            ],
        ),
    ]
