# Generated by Django 4.0 on 2022-01-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0017_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_time_table',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_1.faculty_table'),
        ),
        migrations.AlterField(
            model_name='class_time_table',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_1.subjects_table'),
        ),
    ]
