# Generated by Django 4.0 on 2022-01-31 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0019_alter_lab_time_table_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_time_table',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='v_1.section_table'),
        ),
        migrations.AlterField(
            model_name='class_time_table',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='v_1.semester_table'),
        ),
    ]
