# Generated by Django 4.0.3 on 2022-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0020_alter_class_time_table_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_table',
            name='faculty_short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjects_table',
            name='subject_short_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
