# Generated by Django 4.0.3 on 2022-04-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0022_lab_information_table_lab_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_fac_relation',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_1.faculty_table'),
        ),
        migrations.CreateModel(
            name='Default_class_Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.branch_table')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_1.room_table')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.section_table')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.semester_table')),
            ],
        ),
    ]
