# Generated by Django 4.0.3 on 2022-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0023_alter_sub_fac_relation_faculty_default_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_time_table',
            name='batch',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='class_time_table',
            name='class_type',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
