# Generated by Django 4.0.3 on 2022-05-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_1', '0024_class_time_table_batch_class_time_table_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_time_table',
            name='extra_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_faculty', to='v_1.faculty_table'),
        ),
        migrations.AddField(
            model_name='lab_time_table',
            name='time_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_extra_1', to='v_1.timings_table'),
        ),
        migrations.AddField(
            model_name='lab_time_table',
            name='time_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_extra_2', to='v_1.timings_table'),
        ),
        migrations.CreateModel(
            name='Manual_class_room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_hours', models.IntegerField()),
                ('manual_class', models.CharField(max_length=150)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.branch_table')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.section_table')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.semester_table')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.timings_table')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_1.week_table')),
            ],
        ),
    ]
